<?php

use Illuminate\Database\Seeder;

class August2018ExamCentersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $user = User::where('username','AP01')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','AP01')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','AP02')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','AP02')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','AP04')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','AP04')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','AP14')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','AP14')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','AS01')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','AS01')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','BI06')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','BI06')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','DL05')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','DL05')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','DL07')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','DL07')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','DL11')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','DL11')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','GJ01')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','GJ01')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','GJ08')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','GJ01')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','GJ10')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','GJ02')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','GJ02')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','GJ02')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','GJ04')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','GJ02')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','GJ11')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','GJ11')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','HP02')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','HP02')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','HP03')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','HP03')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','HY03')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','HY03')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','HY04')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','HY04')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','HY07')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','HY07')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','KA05')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','KA05')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','MG01')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','MG01')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','MG02')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','MG02')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','MH18')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','MH18')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','MH28')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','MH28')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','MH29')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','MH29')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','MH30')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','MH30')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','MH31')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','MH31')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','MP05')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','MP05')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','MP07')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','MP07')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','MP15')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','MP15')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','OR02')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','OR02')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','OR03')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','OR03')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','OR04')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','OR04')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','OR08')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','OR08')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','PJ03')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','PJ03')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','RJ02')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','RJ02')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','RJ03')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','RJ03')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','RJ06')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','RJ06')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','RJ19')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','RJ06')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','RJ07')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','RJ07')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','RJ20')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','RJ20')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','TL01')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','TL01')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','TL12')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','TL12')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','UP02')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','UP02')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','UP03')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','UP03')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','UP13')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','UP13')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','UP24')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','UP24')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','UP25')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','UP25')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','UP28')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','UP28')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','UP29')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','UP29')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','UP34')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','UP34')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','WB03')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','WB03')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','WB05')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','WB05')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','WB08')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','WB08')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','WB11')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','WB11')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','WB22')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','WB22')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','KA02')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','KA02')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','KA08')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','KA08')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','KE17')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','KE17')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','TN22')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','TN22')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','TN23')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','TN22')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','KE20')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','KE20')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}

        $user = User::where('username','KE01')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','KE01')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','KE04')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','KE04')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','KE15')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','KE04')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','KE05')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','KE05')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','KE10')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','KE10')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','KE16')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','KE16')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','KE18')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','KE18')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}
        $user = User::where('username','KE19')->first();$institute = Institute::where('user_id',$user->id)->first();$examuser = User::where('username','KE19')->first();$examcenter = Institute::where('user_id',$examuser->id)->first();$ec = Examcenter::where('exam_id', '3')->where('institute_id', $institute->id)->where('examcenter_id', $examcenter->id);if($ec->count() == 0) {Examcenter::create(['examcenter_id'=>$examcenter->id, 'institute_id'=>$institute->id, 'exam_id'=>'3']);}

    }
}
