<?php

use Illuminate\Database\Seeder;
use App\Evaluationcenter;
use App\Externalexamcenter;
use App\Evaluationcenterincharge;
use App\Evaluationcenterdetail;

class EvaluationcenterdetailSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $details = array(
            /*array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXAP11", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXAP12", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXAP13", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXBI03", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXCH04", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXDL02", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXDL03", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXDL04", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXGJ02", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXGJ04", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXHP03", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXHP08", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXHY16", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXHY19", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXHY20", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXHY22", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXHY23", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXHY24", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXHY25", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXJH09", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXJH10", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXKA09", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXKE03", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXKE05", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXKE22", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXKE25", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXKE26", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXMH03", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXMH12", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXMH15", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXMH16", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXMH17", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXMH20", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXMN02", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXMP01", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXMP15", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXMP16", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXMP20", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXOR01", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXOR12", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXPJ07", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXRJ22", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXRJ25", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXRJ26", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXRJ27", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXRJ31", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXRJ32", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXTN01", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXTN08", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXTN10", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXUK02", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXUP01", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXUP15", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXUP41", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXUP53", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXUP57", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXUP59", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXUP60", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXUP61", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXUP62", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXUP63", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXUP64", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXUP65", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXUP66", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXUP67", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXUP69", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXUP70", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXUP71", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXUP73", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXUP75", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXUP76", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXUP78", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXUP79", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXUP81", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXUP83", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXUP85", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXUP86", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXUP87", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXUP88", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXWB01", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXWB13", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN01", "examcentercode" => "EXWB16", "remarks" => "All States", "exam_id" => "18"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXAP03", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXAP10", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXAP11", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXAP12", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXAP13", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXAR01", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXBI03", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXCA01", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXCH02", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXCH04", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXDL02", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXDL03", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXDL04", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXGA03", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXGJ02", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXGJ03", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXGJ04", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXHP03", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXHP08", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXHP09", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXHP10", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXHY16", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXHY19", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXHY20", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXHY21", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXHY22", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXHY23", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXHY24", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXHY25", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXJH05", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXJH07", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXJH08", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXJH09", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXJH10", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXKA03", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXKA04", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXKA09", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXKE03", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXKE05", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXKE09", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXKE17", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXKE19", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXKE20", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXKE21", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXKE22", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXKE23", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXKE24", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXKE25", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXKE26", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXKE27", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXMH03", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXMH12", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXMH15", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXMH16", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXMH17", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXMH18", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXMH19", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXMH20", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXMH21", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXMN02", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXMP01", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXMP13", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXMP14", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXMP15", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXMP16", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXMP17", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXMP18", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXMP19", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXMP20", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXOR01", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXOR09", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXOR10", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXOR11", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXOR12", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXOR13", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXPJ07", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXPJ08", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXPJ09", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXPJ10", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXRJ05", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXRJ21", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXRJ22", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXRJ23", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXRJ24", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXRJ25", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXRJ26", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXRJ27", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXRJ28", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXRJ29", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXRJ30", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXRJ31", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXRJ32", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXRJ33", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXRJ34", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXTL01", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXTN01", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXTN08", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXTN10", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXTN11", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXUK02", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXUP01", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXUP15", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXUP41", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXUP53", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXUP57", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXUP58", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXUP59", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXUP60", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXUP61", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXUP62", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXUP63", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXUP64", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXUP65", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXUP66", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXUP67", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXUP68", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXUP69", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXUP70", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXUP71", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXUP72", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXUP73", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXUP74", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXUP75", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXUP76", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXUP77", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXUP78", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXUP79", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXUP80", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXUP81", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXUP82", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXUP83", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXUP84", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXUP85", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXUP86", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXUP87", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXUP88", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN03", "examcentercode" => "EXUP89", "remarks" => "UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXWB01", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXWB09", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXWB13", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXWB14", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXWB15", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode" => "EVCTN02", "examcentercode" => "EXWB16", "remarks" => "Except UP, RJ, DL", "exam_id" => "19"),
            array("evaluationcentercode"=>"EVCAP01","examcentercode" =>"EXAP05","remarks"=>"Andhra Pradesh ", "exam_id"=>"20"),
            array("evaluationcentercode"=>"EVCAP01","examcentercode"=>"EXAP16","remarks"=>"AndhraPradesh","exam_id"=>"21"),
            array("evaluationcentercode"=>"EVBI01","examcentercode"=>"EXBI04","remarks"=>"Bihar","exam_id"=>"21"),
            array("evaluationcentercode"=>"EVCCA01","examcentercode"=>"EXCA01","remarks"=>"Chandigarh","exam_id"=>"21"),
            array("evaluationcentercode"=>"EVCUP02","examcentercode"=>"EXUP15","remarks"=>"UttarPradesh","exam_id"=>"21"),
            array("evaluationcentercode"=>"EVCGJ01","examcentercode"=>"EXGJ02","remarks"=>"Gujarat","exam_id"=>"21"),
            array("evaluationcentercode"=>"EVCHP01","examcentercode"=>"EXHP03","remarks"=>"HimachalPradesh","exam_id"=>"21"),
            array("evaluationcentercode"=>"EVCJH01","examcentercode"=>"EXJH05","remarks"=>"Jharkhand","exam_id"=>"21"),
            array("evaluationcentercode"=>"EVCKE01","examcentercode"=>"EXKE03","remarks"=>"Kerala","exam_id"=>"21"),
            array("evaluationcentercode"=>"EVCMH01","examcentercode"=>"EXMH26","remarks"=>"Maharashtra","exam_id"=>"21"),
            array("evaluationcentercode"=>"EVCMH02","examcentercode"=>"EXMH03","remarks"=>"Maharashtra","exam_id"=>"21"),
            array("evaluationcentercode"=>"EVCMP01","examcentercode"=>"EXMP01","remarks"=>"MadhyaPradesh","exam_id"=>"21"),
            array("evaluationcentercode"=>"EVCOR01","examcentercode"=>"EXOR18","remarks"=>"Odisha","exam_id"=>"21"),
            array("evaluationcentercode"=>"EVCTL16","examcentercode"=>"EXTL01","remarks"=>"telangana","exam_id"=>"21"),
            array("evaluationcentercode"=>"EVCUK01","examcentercode"=>"EXUK03","remarks"=>"Uttarakhand","exam_id"=>"21"),
            array("evaluationcentercode"=>"EVCUP01","examcentercode"=>"EXUP01","remarks"=>"UttarPradesh","exam_id"=>"21"),
            array("evaluationcentercode"=>"EVCUP03","examcentercode"=>"EXUP23","remarks"=>"UttarPradesh","exam_id"=>"21"),
            array("evaluationcentercode"=>"EVCWB01","examcentercode"=>"EXWB20","remarks"=>"Westbengal","exam_id"=>"21"),
            array("evaluationcentercode"=>"EVCKA09","examcentercode"=>"EXKA04","remarks"=>"Karnataka","exam_id"=>"21"),*/
            array("evaluationcentercode"=>"EVCUP01","examcentercode"=>"EXRJ56","remarks"=>"UttarPradesh","exam_id"=>"21"),
            array("evaluationcentercode"=>"EVCUP01","examcentercode"=>"EXRJ57","remarks"=>"UttarPradesh","exam_id"=>"21"),
            array("evaluationcentercode"=>"EVCUP01","examcentercode"=>"EXHY09","remarks"=>"UttarPradesh","exam_id"=>"21"),

            

        );

        foreach ($details as $d) {
            $evaluationcenterid = Evaluationcenter::where("code", $d["evaluationcentercode"])->first()->id;

            if(!is_null($evaluationcenterid)) {
                $examcenterid = Externalexamcenter::where("code", $d["examcentercode"])->first()->id;

                if(!is_null($examcenterid)) {
                    $evaluationcenterdetail = Evaluationcenterdetail::where("exam_id", $d["exam_id"])->where("evaluationcenter_id", $evaluationcenterid)
                        ->where("externalexamcenter_id", $examcenterid)->first();

                    if(is_null($evaluationcenterdetail)) {
                        Evaluationcenterdetail::create([
                            "exam_id" => $d["exam_id"],
                            "evaluationcenter_id" => $evaluationcenterid,
                            "externalexamcenter_id" => $examcenterid,
                            "remarks" => $d["remarks"],
                            "active_status" => 1
                        ]);
                    }
                    else {
                        $evaluationcenterdetail->update([
                            "exam_id" => $d["exam_id"],
                            "evaluationcenter_id" => $evaluationcenterid,
                            "externalexamcenter_id" => $examcenterid,
                            "remarks" => $d["remarks"],
                            "active_status" => 1
                        ]);
                    }
                }
            }
        }

    }
}
