<?php

use Illuminate\Database\Seeder;
use App\User;
use App\Institute;

class InstituteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $institute_array = array(
            array("code" => "AP01", "name" => "Rass College of Special Education",),
            array("code" => "AP02", "name" => "Pragathi Charities College of Special Education",),
            array("code" => "AP03", "name" => "Sweekar Academy of Rehabilitation Sciences",),
            array("code" => "AP04", "name" => "Uma Educational and Technical Society",),
            array("code" => "AP05", "name" => "Kasinadhuni Durgamba Butchaiah Trust",),
            array("code" => "AP06", "name" => "M.N.R. College of Special Education",),
            array("code" => "AP07", "name" => "Integrated Special Education",),
            array("code" => "AP09", "name" => "St. Ann's College for DSE (MR)",),
            array("code" => "AP10", "name" => "Little Star College of Special Education",),
            array("code" => "AP11", "name" => "Helping Hands College for Diploma in Special Education",),
            array("code" => "AP12", "name" => "S.V. College of Special Education",),
            array("code" => "AP13", "name" => "Chaithanya College of D.Ed. Spl. Ed. (MR)",),
            array("code" => "AP14", "name" => "Helen Keller's College of Special Education",),
            array("code" => "AP15", "name" => "St. Andrews College of Special Education",),
            array("code" => "AP16", "name" => "B.G. College of Special Education",),
            array("code" => "AR01", "name" => "Himalayan University",),
            array("code" => "AS01", "name" => "Shishu Sarothi Centre for Rehabilitation & Training for Multiple Disability",),
            array("code" => "AS02", "name" => "Composite Regional Centre for Skill Development, Rehabilitation & Empowerment of Persons with Disabilities",),
            array("code" => "BI01", "name" => "J.M. Institute of Speech & Hearing",),
            array("code" => "BI02", "name" => "S.L. Roy Public Health & Research Institute",),
            array("code" => "BI03", "name" => "Environmental Consultancy Vikash Centre (ECOVIC)",),
            array("code" => "BI04", "name" => "J.M. Institute of Speech & Hearing",),
            array("code" => "BI05", "name" => "Indian Institute of Health Education & Research",),
            array("code" => "BI06", "name" => "Ayurvedic & Magnetotherapy Research Institute",),
            array("code" => "BI08", "name" => "Composite Regional Centre for Skill Development, Rehabilitation & Empowerment of Persons with Disabilities",),
            array("code" => "BI09", "name" => "Utakarsh Rehabilitation & Research Institute",),
            array("code" => "CA02", "name" => "Indian National Portage Association",),
            array("code" => "CA03", "name" => "Govt. Rehabilitation Institute for Intellectual Disabilities (GRIID)",),
            array("code" => "CH02", "name" => "Aakanksha, Lions School for the Mentally Handicapped",),
            array("code" => "CH03", "name" => "Piyali Foundation College for Special Education",),
            array("code" => "CH04", "name" => "Composite Regional Centre for Skill Development, Rehabilitation & Empowerment of Persons with Disabilities",),
            array("code" => "CH05", "name" => "Piyali Teacher Training Institute",),
            array("code" => "DL01", "name" => "Action for Autism ",),
            array("code" => "DL03", "name" => "Ashtavakra Institute of Rehabilitation Sciences & Research, (PSP)",),
            array("code" => "DL04", "name" => "Tamana Association (School of Hope)",),
            array("code" => "DL05", "name" => "Vision Institute of Advanced Studies",),
            array("code" => "DL06", "name" => "Ashtavakra Institute of Rehabilitation Sciences & Research, (BD-1)",),
            array("code" => "DL07", "name" => "Manovikas Comprehensive Rehabilitation and Research Centre",),
            array("code" => "DL08", "name" => "Teachers Training Institute for Special Education",),
            array("code" => "DL09", "name" => "C.B.S. Memorial Mahila, Bal Evam Shravan Viklang Shiksha Evam Punarvas Sansthan",),
            array("code" => "DL10", "name" => "Teachers Training Institute for Special Education",),
            array("code" => "DL11", "name" => "Amar Jyoti Rehabilitation and Research Centre",),
            array("code" => "DL12", "name" => "Viklang Avam Punarvas Kendra",),
            array("code" => "DL13", "name" => "K.S. Memorial College for Research and Rehabilitation",),
            array("code" => "DL14", "name" => "Association for Advancement & Rehabilitation of Handicapped (AAROH)",),
            array("code" => "DL15", "name" => "CBSM",),
            array("code" => "DL16", "name" => "Shristi",),
            array("code" => "DL17", "name" => "National Trust for the Handicapped",),
            array("code" => "GA01", "name" => "Lokvishwas Pratishthan",),
            array("code" => "GA02", "name" => "Sanjay Centre for Special Education",),
            array("code" => "GJ01", "name" => "Smt. PNR Society, (Talajwala) Society for Relief & Rehabilitation of the Disabled",),
            array("code" => "GJ02", "name" => "Gujarat Kelvani Trust",),
            array("code" => "GJ04", "name" => "B.M. Institute of Mental Health",),
            array("code" => "GJ05", "name" => "B.Ed College for the Special Education",),
            array("code" => "GJ06", "name" => "Medical Care Centre Trust",),
            array("code" => "GJ07", "name" => "Blind Welfare Council",),
            array("code" => "GJ08", "name" => "Ankur Special School for Mentally Retarded Children",),
            array("code" => "GJ09", "name" => "Composite Regional Centre for Skill Development, Rehabilitation & Empowerment of Persons with Disabilities",),
            array("code" => "GJ10", "name" => "Sh.Shah K.L.Institute for the Deaf",),
            array("code" => "GJ11", "name" => "Akshar Trust",),
            array("code" => "HP01", "name" => "Composite Regional Centre for Skill Development, Rehabilitation & Empowerment of Persons with Disabilities",),
            array("code" => "HP02", "name" => "Prem Ashram Institute of Sisters of Charity",),
            array("code" => "HP03", "name" => "Chetna Association",),
            array("code" => "HP04", "name" => "Aastha Special School",),
            array("code" => "HY01", "name" => "Society for Advanced Study in Rehabilitation (SASR)",),
            array("code" => "HY03", "name" => "Vision Institute for Applied Studies",),
            array("code" => "HY04", "name" => "Adarsh Rehabilitation Centre for Mentally and Physically Handicapped Children",),
            array("code" => "HY05", "name" => "Misri Devi Rehabilitation Centre",),
            array("code" => "HY06", "name" => "Jind Central Jaycees Education and Charitable Society",),
            array("code" => "HY07", "name" => "MR DAV College of Education",),
            array("code" => "HY08", "name" => "Red Cross Hindu Institute for Education and Rehabilitation of Mentally Challenged Children",),
            array("code" => "HY09", "name" => "State Institute for Rehabilitation Training & Research (SIRTAR)",),
            array("code" => "HY10", "name" => "Amar Jyoti Foundation",),
            array("code" => "HY11", "name" => "Arpan Institute for the Mentally Handicapped",),
            array("code" => "HY12", "name" => "Shivom Rehabilitation Centre (SRC)",),
            array("code" => "HY13", "name" => "Haryana College of Special Education & Rehabilitation",),
            array("code" => "HY15", "name" => "Rural Community Development Project",),
            array("code" => "HY16", "name" => "S.M. Rehabilitation & Research Centre",),
            array("code" => "HY17", "name" => "Arya Rehabilitation Training Centre",),
            array("code" => "HY18", "name" => "Aanchal Rehabilitation Centre",),
            array("code" => "HY19", "name" => "Aanchal Rehabilitation Centre",),
            array("code" => "HY20", "name" => "KVM College of Education",),
            array("code" => "HY21", "name" => "Maa Sharda Institute for Rehabilitation Training & Research",),
            array("code" => "HY22", "name" => "Renu Vidya Mandir (An Institute of Special Education)",),
            array("code" => "HY23", "name" => "Samarth Institute of Inclusive Education",),
            array("code" => "HY24", "name" => "Asha Kiran Institute of Rehabilitation",),
            array("code" => "HY25", "name" => "Teerthanker K.R.D. College",),
            array("code" => "HY26", "name" => "JBDM Rehabilitation Centre for Mentally and Physically Disabled Students",),
            array("code" => "HY27", "name" => "J.B.D.M College of Special Education",),
            array("code" => "HY28", "name" => "St. Paul College of Education",),
            array("code" => "HY29", "name" => "Institute for Advanced Research and Social Action",),
            array("code" => "HY30", "name" => "Adarsh Rehabilitation Institute of Vocational Training",),
            array("code" => "HY31", "name" => "Aadhar College of Special Education",),
            array("code" => "HY32", "name" => "Green Valley Institute of Special Education & Rehabilitation Centre",),
            array("code" => "HY33", "name" => "Ideal College of Special Education",),
            array("code" => "HY34", "name" => "J.M. Rehabilitation and Research Center",),
            array("code" => "JH01", "name" => "J.M. Institute of Speech & Hearing",),
            array("code" => "JH02", "name" => "J.M. Institute of Speech & Hearing",),
            array("code" => "JH03", "name" => "Deepshikha Institute for Child Development & Mental Health",),
            array("code" => "JH04", "name" => "Prerna Trust",),
            array("code" => "JH05", "name" => "Radhika Institute of Special Education (RISE)",),
            array("code" => "JH06", "name" => "Buddha Shaikshanik Vikas Parishad",),
            array("code" => "JH07", "name" => "Deaf Dumb & M.R. Residential School Cum Resource Centre",),
            array("code" => "JH08", "name" => "Sparsh",),
            array("code" => "JH09", "name" => "Jeevan",),
            array("code" => "JH11", "name" => "Green Valley Training College",),
            array("code" => "JH12", "name" => "Aastha Institute of Special Education",),
            array("code" => "JK01", "name" => "Composite Regional Centre for Skill Development, Rehabilitation & Empowerment of Persons with Disabilities",),
            array("code" => "KA01", "name" => "The Spastics Society of Karnataka",),
            array("code" => "KA02", "name" => "Association of People with Disability (APD)",),
            array("code" => "KA03", "name" => "Information & Resource Centre (IRC) for Autism & Other Developmental Disabilities",),
            array("code" => "KA04", "name" => "St. Agnes Teacher Training Institute for the Special Education",),
            array("code" => "KA05", "name" => "Karnataka Parents’ Association for the Mentally Retarded Citizens",),
            array("code" => "KA06", "name" => "Foundation for Action Motivation & Empowerment (F.A.M.E.)",),
            array("code" => "KA07", "name" => "Asha Kirana School for the Mentally Retarded",),
            array("code" => "KA08", "name" => "Mobility India",),
            array("code" => "KE01", "name" => "K.V.M College of Special Education",),
            array("code" => "KE03", "name" => "Raksha Society for the Care of Children with Special Needs",),
            array("code" => "KE04", "name" => "Kusumagiri Training Institute for Special Education",),
            array("code" => "KE05", "name" => "C.H. Mohammed Koya Memorial State Institute for the Mentally Challenged (SIMC)",),
            array("code" => "KE06", "name" => "Nirmala Sadan Training College for Special Education",),
            array("code" => "KE07", "name" => "Faith India Institute of Special Education",),
            array("code" => "KE08", "name" => "Government Special Teachers Training Centre",),
            array("code" => "KE09", "name" => "Government Special Teachers Training Centre",),
            array("code" => "KE10", "name" => "Sneha Sadan College of Special Education",),
            array("code" => "KE11", "name" => "AWH College of Education",),
            array("code" => "KE11", "name" => "AWH Institute for the Mentally Handicapped",),
            array("code" => "KE12", "name" => "RSMH Teacher Training Institute",),
            array("code" => "KE13", "name" => "Pope Paul Mercy Home Teachers Training Centre",),
            array("code" => "KE14", "name" => "Central Institute on Mental Retardation",),
            array("code" => "KE15", "name" => "Janey College of Allied Health",),
            array("code" => "KE16", "name" => "St. John of God College of Special Education",),
            array("code" => "KE17", "name" => "Yemvees Institute for Prosthetics & Orthotics",),
            array("code" => "KE18", "name" => "Composite Regional Centre for Skill Development, Rehabilitation & Empowerment of Persons with Disabilities",),
            array("code" => "KE19", "name" => "St.John Baptist's College of Special Education",),
            array("code" => "KE20", "name" => "Training Institute of Multi Rehabilitation Technology “Mercy Home”",),
            array("code" => "MG01", "name" => "Monfort Centre for Education",),
            array("code" => "MG02", "name" => "Bethany Society",),
            array("code" => "MH01", "name" => "Yashratna College of Special Education Mental Retardation",),
            array("code" => "MH02", "name" => "Shri. Balaji Shikshan Prasarak Mandal",),
            array("code" => "MH04", "name" => "Surya Teachers Training Centre",),
            array("code" => "MH05", "name" => "Dr. Babasaheb Ambedkar Teacher Training Institute",),
            array("code" => "MH06", "name" => "Dilkush Teachers Training in Special Education",),
            array("code" => "MH07", "name" => "Acharya Balashastri Jambhekar College of Special Education",),
            array("code" => "MH09", "name" => "Jeevoday College of Special Education (MR)",),
            array("code" => "MH10", "name" => "Jeevan Vikas Pratisthan’s Institute of Special Education Rehabilitation Research & Training Center",),
            array("code" => "MH11", "name" => "Adarsh Sanskar College of Special Education",),
            array("code" => "MH12", "name" => "Swarswata (DSE) Vidyalaya",),
            array("code" => "MH13", "name" => "Dr. Sarvapalli Radhakrishnan College of Special Education",),
            array("code" => "MH14", "name" => "Shri Samarth Vyayam Mandal(s) Teacher's Training Centre",),
            array("code" => "MH15", "name" => "Sharadchandra Pawar College of Special Education",),
            array("code" => "MH16", "name" => "Shri Gajanan Maharaj College of Special Education for Mental Retardation",),
            array("code" => "MH17", "name" => "Asha College of Special Education",),
            array("code" => "MH18", "name" => "Pradip M Pande D.Ed Spl MR College",),
            array("code" => "MH19", "name" => "Sewayog Special Education College",),
            array("code" => "MH20", "name" => "Yashoda Shikshan Prasarak Mandals Sojar Teachers Training Centre",),
            array("code" => "MH21", "name" => "Eshwari Bai Lund Training Centre for DSE (MR) College",),
            array("code" => "MH23", "name" => "Chamundamata Bahuuddeshjiya Vikas Parisar",),
            array("code" => "MH24", "name" => "Yash Special Teacher Training Institute ",),
            array("code" => "MH25", "name" => "National Institute for the Mentally Handicapped",),
            array("code" => "MH26", "name" => "Aadhar Shikshan Va Gramin Vikas Mandal’s Sai Seva Teachers Training Centre DSE (MR)",),
            array("code" => "MH27", "name" => "Wai Akshar Institute",),
            array("code" => "MH29", "name" => "Shri. Sant Gadge Maharaj Bahuuddeshiya Shikshan Sanstha",),
            array("code" => "MH30", "name" => "Rashtriya Drushtihin Shikshan & Punarvas Sanstha",),
            array("code" => "MH31", "name" => "NAWPH College of Special Education, National Association for the Welfare of the Physically Handicapped ",),
            array("code" => "MH32", "name" => "Swami Vivekanand College of Special Education",),
            array("code" => "MN01", "name" => "All Manipur Mentally Handicapped Person’s Welfare Organisation",),
            array("code" => "MP03", "name" => "Shiv Kalyan Evam Shikshan Samiti",),
            array("code" => "MP04", "name" => "Composite Regional Centre for Skill Development, Rehabilitation & Empowerment of Persons with Disabilities",),
            array("code" => "MP05", "name" => "Digdarshika Institute of Rehabilitation & Research",),
            array("code" => "MP06", "name" => "Sharada Arunoday Kalyankari Shiksha Samiti",),
            array("code" => "MP07", "name" => "Viklang Seva Bharti",),
            array("code" => "MP08", "name" => "Amar Jyoti School & Rehabilitation Center",),
            array("code" => "MP09", "name" => "Rajrani Sewa Avam Shikshan Prashikshan Sansthan and Social Welfare Society",),
            array("code" => "MP10", "name" => "Gurukul College of Special Education",),
            array("code" => "MP11", "name" => "Madhuri Aayaam Education and Welfare Society",),
            array("code" => "MP12", "name" => "New Era College of Special Education",),
            array("code" => "MP13", "name" => "Bhagwan Singh Social Welfare Foundation Society",),
            array("code" => "MP14", "name" => "Bhagwan Singh Social Welfare Foundation Society",),
            array("code" => "MP15", "name" => "Manovikas College of Special Education (M.P. Viklang Sahayata Samiti)",),
            array("code" => "MP16", "name" => "Bardoli Jankal Evam Vikas Samiti",),
            array("code" => "MZ01", "name" => "NERC-NIOH (Dept. for Empowerment of PWD's MSJ & E, GOI)",),
            array("code" => "OR01", "name" => "Open Learning Systems",),
            array("code" => "OR02", "name" => "Jewels International’s Chetana College of Special Education",),
            array("code" => "OR03", "name" => "D.P. Mishra Institute for Advance Studies in Special Education & Technology",),
            array("code" => "OR04", "name" => "Disability Rehabilitation and Training Centre (Nilachal Seva Pratisthan)",),
            array("code" => "OR05", "name" => "Bijupatnaik Institute of Industrial Rehabilitation Training & Research",),
            array("code" => "OR06", "name" => "Union for Learning Training and Reformative Activities",),
            array("code" => "OR08", "name" => "Pingalakhi Public Welfare Organisation",),
            array("code" => "OR09", "name" => "Jibanjyoti College of Special Education",),
            array("code" => "OR10", "name" => "Seva Training Centre for Teachers of the Mentally Retarded",),
            array("code" => "OR11", "name" => "Jewels International Chetana College of Special Education",),
            array("code" => "PJ01", "name" => "Navjivini Institute of Special Education & Research",),
            array("code" => "PJ02", "name" => "Saint Francis Home (Regd.) Society",),
            array("code" => "PJ03", "name" => "Jagjit Singh Sachdeva Asha Kiran Special School",),
            array("code" => "PJ04", "name" => "Baba Kundan Rural College of Education",),
            array("code" => "PJ05", "name" => "Speaking Hand Welfare Foundation",),
            array("code" => "PJ06", "name" => "Bhagat Puran Singh Institute for Special Needs",),
            array("code" => "RJ01", "name" => "Disha - A Resource Centre for the Disabled",),
            array("code" => "RJ02", "name" => "Shree Nirmal Vivek School",),
            array("code" => "RJ03", "name" => "Manav Dharam Mentally Retarded Teachers Training Centre",),
            array("code" => "RJ04", "name" => "Dashrath Manovikas Sansthan",),
            array("code" => "RJ05", "name" => "Prayas: Centre for Special Education & Vocational Training",),
            array("code" => "RJ06", "name" => "Tapovan Manovikas Vidyalaya",),
            array("code" => "RJ07", "name" => "Rajasthan Mahila Kalyan Mandal",),
            array("code" => "RJ08", "name" => "Karam Mano Vikas Sansthan",),
            array("code" => "RJ09", "name" => "Gurukul Spastic Society",),
            array("code" => "RJ10", "name" => "Navjyoti Manovikas Kendra",),
            array("code" => "RJ11", "name" => "Diya Institute of Special Education & Research Centre (Chaitanya Seva Sansthan)",),
            array("code" => "RJ12", "name" => "Sona Viklang Punerwas Avom Sodh Sansthan",),
            array("code" => "RJ13", "name" => "Late Rajesh Pilot Smriti Gram Udhyog Shiksha Samiti",),
            array("code" => "RJ14", "name" => "Garima Special School Samiti",),
            array("code" => "RJ15", "name" => "Lakshya Sansthan Lakshya Rehabilitation Centre",),
            array("code" => "RJ16", "name" => "Nav Chetna Mansik Viklang & Mook Badhir Vidhyalay Samiti",),
            array("code" => "RJ17", "name" => "Sambal Samiti",),
            array("code" => "RJ18", "name" => "Ishom Special Teacher Training Centre",),
            array("code" => "RJ19", "name" => "L.K.C. Jagdamba Andh Vidyalaya Samiti",),
            array("code" => "RJ20", "name" => "Ajay Leela Special Teachers Training College",),
            array("code" => "RJ21", "name" => "Nehru Adarsh Jan Swasthya Gramin Vikash Sanstha",),
            array("code" => "RJ22", "name" => "Rudraksh Educational and Welfare Society",),
            array("code" => "RJ23", "name" => "Indian Institute of Learning Disabilities & Rehabilitation",),
            array("code" => "RJ24", "name" => "S.V.N. Sansthan",),
            array("code" => "RJ25", "name" => "Shekhawati Teachers Training Institute",),
            array("code" => "RJ26", "name" => "Salasar Balaji B.Ed College",),
            array("code" => "RJ27", "name" => "Aoes Teacher Training Centre",),
            array("code" => "RJ28", "name" => "Mansik Viklang Shikshan Prashikshan Kendra",),
            array("code" => "RJ29", "name" => "Srijan Manav Shiksha Avam Kalyan Sansthan",),
            array("code" => "RJ30", "name" => "Shri Rudra Special Teacher Training Center",),
            array("code" => "RJ31", "name" => "Shivam Special Teacher Training Center",),
            array("code" => "TL01", "name" => "Thakur Hari Prasad  Institute of Research & Rehabilitation for the Mentally Handicapped",),
            array("code" => "TL05", "name" => "Child Guidance Centre",),
            array("code" => "TL06", "name" => "Sannidhi Center for Life Skills",),
            array("code" => "TL07", "name" => "Manochetana, Chukka Ramaiah Marg",),
            array("code" => "TL08", "name" => "National Institute for the Empowerment of Persons with Intellectual Disabilities",),
            array("code" => "TL09", "name" => "Durgabai Deshmukh Vocational Training and Rehabilitation Centre for Handicapped",),
            array("code" => "TL10", "name" => "Padmanayaka College of Spl. Edn.",),
            array("code" => "TL11", "name" => "Holy Faith College of Special Education D.Ed-Deaf & Hard of Hearing",),
            array("code" => "TL12", "name" => "Helen Keller's Institute of Research and Rehabilitation for the Disabled Children",),
            array("code" => "TL13", "name" => "Ashray Akruti",),
            array("code" => "TN01", "name" => "Amar Seva Sangam, Sulochana Gardens",),
            array("code" => "TN02", "name" => "National Institute for Empowerment of Persons with Multiple Disabilities (NIEPMD)",),
            array("code" => "TN05", "name" => "The Spastics Society of Tamilnadu",),
            array("code" => "TN06", "name" => "Spastic Society of Tiruchirapalli",),
            array("code" => "TN11", "name" => "Holy Cross College",),
            array("code" => "TN12", "name" => "Paul Institute of Special Teacher Training",),
            array("code" => "TN13", "name" => "SCAD Resource Centre for Differently Abled",),
            array("code" => "TN14", "name" => "Vijay Human Services",),
            array("code" => "TN15", "name" => "Mrs. Ann Fischer Memorial Training Institute for Special Education",),
            array("code" => "TN16", "name" => "Bala Vihar Training School",),
            array("code" => "TN17", "name" => "C.S.I Balar Gnana Illam",),
            array("code" => "TN18", "name" => "Madhuram Narayanan Centre for Exceptional Children",),
            array("code" => "TN20", "name" => "S.B.T. College of Special Education",),
            array("code" => "TN21", "name" => "National Institute for Empowerment of Persons with Multiple Disabilities, Extension Center",),
            array("code" => "TN22", "name" => "Christian Medical College (CMC)",),
            array("code" => "TN23", "name" => "Schieffelin Institute of Health - Research & Leprosy Centre",),
            array("code" => "UK01", "name" => "Raphael Ryder Cheshire International Centre",),
            array("code" => "UP02", "name" => "Institute of Rehabilitation",),
            array("code" => "UP03", "name" => "Integrated Institute for the Disabled",),
            array("code" => "UP04", "name" => "Jyoti Institute of Medical & Rehabilitation Sciences (JIMARS)",),
            array("code" => "UP05", "name" => "Kiran Society",),
            array("code" => "UP09", "name" => "Maharishi Dayanand Rehabilitation Institute",),
            array("code" => "UP10", "name" => "Chetna (A Society of the Welfare of Handicapped)",),
            array("code" => "UP11", "name" => "Meerut Institute of Special Education (MISE)",),
            array("code" => "UP12", "name" => "Lt. Sh. Jagat Narayan Training College for Mentally Handicapped",),
            array("code" => "UP13", "name" => "Navada Gram Udyog Vikas Samiti’s Ali Mobeen Memorial Institute for Handicapped",),
            array("code" => "UP14", "name" => "National Institute for the Mentally Handicapped",),
            array("code" => "UP15", "name" => "Shubhasheesh Shiksha Evam Vikas Sewa Sansthan",),
            array("code" => "UP16", "name" => "Sri Mahadew Jee Ram Adhar Biklang Shikshan Prashikshan Kendra",),
            array("code" => "UP17", "name" => "Vasudha Kalyani Special Education Institute",),
            array("code" => "UP18", "name" => "Jay Nand Special Teachers’ Training Institute",),
            array("code" => "UP19", "name" => "Gyanvati Memorial Shikshan Sansthan",),
            array("code" => "UP20", "name" => "Composite Regional Centre for Skill Development, Rehabilitation & Empowerment of Persons with Disabilities",),
            array("code" => "UP21", "name" => "CBSM, Raebareli Speech & Hearing Institute",),
            array("code" => "UP22", "name" => "Handicapped Development Council",),
            array("code" => "UP23", "name" => "K.S. Memorial",),
            array("code" => "UP24", "name" => "Rachna Vishesh Vidyalaya",),
            array("code" => "UP25", "name" => "Gyanodaya Samekit Sansthan",),
            array("code" => "UP26", "name" => "Pramila Katiyar Special Education Institute",),
            array("code" => "UP27", "name" => "Pyssum Research & Training Centre",),
            array("code" => "UP28", "name" => "Gramodyog Sewa Sansthan",),
            array("code" => "UP29", "name" => "Kalyanam Karoti",),
            array("code" => "UP30", "name" => "Amar Jyoti Institute of Special Education",),
            array("code" => "UP31", "name" => "Amar Jyoti Sansthan",),
            array("code" => "UP32", "name" => "Vishal Institute of Rehabilitation Sciences",),
            array("code" => "UP33", "name" => "Vasudha Kalyani Mand Buddhi Viklang Vidyalaya",),
            array("code" => "UP34", "name" => "Maa Baliraji Seva Sansthan",),
            array("code" => "UP35", "name" => "Samman (Branch of Integrated Institute for the Disabled)",),
            array("code" => "UP36", "name" => "Usha Charitable Trust",),
            array("code" => "UP37", "name" => "Society for Institute of Psychological Research & Health",),
            array("code" => "UP38", "name" => "Sanskriti University School of Rehabilitation",),
            array("code" => "UP39", "name" => "Institute of Rehabilitation and Allied Studies",),
            array("code" => "UP40", "name" => "College of Higher Studies",),
            array("code" => "UP41", "name" => "Smt. Fulehra Vishisht B.T.C. Prashikshan Kendra",),
            array("code" => "UP42", "name" => "Saurabh Shobhit Shikshan Prashikshan Kendra",),
            array("code" => "UP43", "name" => "Sankalp",),
            array("code" => "UP44", "name" => "Patel Shiksha Samiti",),
            array("code" => "UP45", "name" => "K.S. Memorial College for Research and Rehabilitation",),
            array("code" => "UP46", "name" => "Hind Mahavidyalay",),
            array("code" => "UP47", "name" => "Happiness Teachers Training Institute",),
            array("code" => "UP48", "name" => "Chaudhary Charan Singh Institute of Special Education",),
            array("code" => "UP49", "name" => "ITM Institute of Higher Education",),
            array("code" => "UP50", "name" => "Prakash Kiran Educational Institution",),
            array("code" => "UP51", "name" => "Sarveshwari Shikshan Sansthan",),
            array("code" => "UP52", "name" => "Shanti Niketan Special School",),
            array("code" => "UP53", "name" => "Yuva Viklang Evam Dristibadhitrath Sewa Sansthan",),
            array("code" => "UP54", "name" => "Sri Dayal Janhit Shikshan Sansthan",),
            array("code" => "UP55", "name" => "Krishna Jan Kalyan Sikshan Sansthan",),
            array("code" => "UP56", "name" => "Bharat Mata Samajotthan Samiti",),
            array("code" => "UP57", "name" => "Anchal Foundation",),
            array("code" => "UP58", "name" => "Purvanchal Shiksha Samiti",),
            array("code" => "UP59", "name" => "Bhartiya Chauhan Samiti",),
            array("code" => "UP60", "name" => "Jai Maa Saraswati Sewa Sansthan",),
            array("code" => "UP61", "name" => "Sarrthi Institute of Developmental Studies",),
            array("code" => "UP62", "name" => "Integrated Institute of Rehabilitation for the Disabled (Viklang Samekit Punarwas Sansthan)",),
            array("code" => "UP63", "name" => "Cross Belly Rehabilitation Sansthan",),
            array("code" => "UP64", "name" => "Gyanodaya Samekit Sansthan",),
            array("code" => "UP65", "name" => "Shanti Niketan College of Business Management and Computer Science",),
            array("code" => "UP66", "name" => "Suveera Institute for Rehabilitation and Disabilities",),
            array("code" => "UP67", "name" => "Shree Kailash Disability and Rehabilitation Society",),
            array("code" => "UP68", "name" => "Lucknow College of Rehabilitation Studies",),
            array("code" => "UP69", "name" => "Shri Bajrangi Singh Shiksha Samiti",),
            array("code" => "UP70", "name" => "L.R.S. World College",),
            array("code" => "UP71", "name" => "Jainath Memorial Rehabilitation Sansthan",),
            array("code" => "UP72", "name" => "Maa Yashoda Memorial Shikshak Prashikshan Sansthan",),
            array("code" => "UP73", "name" => "Shree Chandra Bhan Singh Degree College",),
            array("code" => "UP74", "name" => "Shree Mahavir College",),
            array("code" => "UP75", "name" => "Sri Maruti College of Research and Rehabilitation",),
            array("code" => "UP76", "name" => "Ram Murat Smarak Shikshan Seva Sameeti",),
            array("code" => "UP77", "name" => "Smt. Shubhraji Devi Degree College",),
            array("code" => "WB02", "name" => "Pradip Centre for Autism Management",),
            array("code" => "WB03", "name" => "Manovikas Kendra, Rehabilitation and Research Institute for the Handicapped",),
            array("code" => "WB04", "name" => "Alakendu Bodh Niketan Residential",),
            array("code" => "WB05", "name" => "Shelter College of Special Education",),
            array("code" => "WB06", "name" => "Bikashayan",),
            array("code" => "WB07", "name" => "Cooch Behar Special Education Teachers Training Centre",),
            array("code" => "WB08", "name" => "North Bengal Handicapped Rehabilitation Society",),
            array("code" => "WB09", "name" => "Midnapore Rehabilitation Centre for Children",),
            array("code" => "WB10", "name" => "Anandniketan (Society for Mental Health Care)",),
            array("code" => "WB11", "name" => "Debendranath Mondal (D.N. Mondal) College",),
            array("code" => "WB12", "name" => "Nadia Zilla Pratibandhi Kalyan Samiti",),
            array("code" => "WB13", "name" => "Moyna Ramkrishnayan Association",),
            array("code" => "WB14", "name" => "Vivekananda Lokshiksha Niketan",),
            array("code" => "WB16", "name" => "National Institute for the Mentally Handicapped Regional Training Centre",),
            array("code" => "WB17", "name" => "Autism Society West Bengal",),
            array("code" => "WB18", "name" => "Asha Bhavan Centre",),
            array("code" => "WB19", "name" => "Punarbasan - A Centre for Special Education",),
            array("code" => "WB20", "name" => "Tarai and Dooars Special Education Training College",),
            array("code" => "WB21", "name" => "New Mission Training College",),
            array("code" => "WB22", "name" => "Voice of World",),

        );

        foreach ($institute_array as $ia) {
            $institute = Institute::where('code', $ia["code"])->first();

            if(!is_null($institute)) {
                $institute->update([
                    "name" => $ia["name"],
                ]);
            }
        }

    }
}
