
<?php

use Illuminate\Database\Seeder;
use App\Candidate;
use App\Subject;
use App\Mark;
use App\Markcertificate;
use App\Application;

class OldDataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      $candidate=Candidate::where('enrolmentno','271601401')->first(); $subject = Subject::where('scode','01MDID')->first(); $application = Application::create(['subject_id'=>$subject->id,'status_id'=>'1','term'=>'1','language_id'=>'1','candidate_id'=>$candidate->id,'exam_id'=>'1']);Mark::create(['application_id'=>$application->id, 'internal'=>'28','external'=>'36','result_id'=>'1']);
      $candidate=Candidate::where('enrolmentno','271601401')->first(); $subject = Subject::where('scode','01MDEP')->first(); $application = Application::create(['subject_id'=>$subject->id,'status_id'=>'1','term'=>'1','language_id'=>'1','candidate_id'=>$candidate->id,'exam_id'=>'1']);Mark::create(['application_id'=>$application->id, 'exam_id'=>'1', 'candidate_id'=>$candidate->id, 'subject_id'=>$subject->id, 'internal'=>'26','external'=>'35','result_id'=>'1']);
      $candidate=Candidate::where('enrolmentno','271601401')->first(); $subject = Subject::where('scode','01MDHD')->first(); $application = Application::create(['subject_id'=>$subject->id,'status_id'=>'1','term'=>'1','language_id'=>'1','candidate_id'=>$candidate->id,'exam_id'=>'1']);Mark::create(['application_id'=>$application->id, 'exam_id'=>'1', 'candidate_id'=>$candidate->id, 'subject_id'=>$subject->id, 'internal'=>'28','external'=>'32','result_id'=>'1']);
      $candidate=Candidate::where('enrolmentno','271601401')->first(); $subject = Subject::where('scode','01MDEA')->first(); $application = Application::create(['subject_id'=>$subject->id,'status_id'=>'1','term'=>'1','language_id'=>'1','candidate_id'=>$candidate->id,'exam_id'=>'1']);Mark::create(['application_id'=>$application->id, 'exam_id'=>'1', 'candidate_id'=>$candidate->id, 'subject_id'=>$subject->id, 'internal'=>'29','external'=>'41','result_id'=>'1']);
      $candidate=Candidate::where('enrolmentno','271601401')->first(); $subject = Subject::where('scode','01MDAA')->first(); $application = Application::create(['subject_id'=>$subject->id,'status_id'=>'1','term'=>'1','language_id'=>'1','candidate_id'=>$candidate->id,'exam_id'=>'1']);Mark::create(['application_id'=>$application->id, 'exam_id'=>'1', 'candidate_id'=>$candidate->id, 'subject_id'=>$subject->id, 'internal'=>'26','external'=>'41','result_id'=>'1']);
      $candidate=Candidate::where('enrolmentno','271601401')->first(); $subject = Subject::where('scode','01MDTM')->first(); $application = Application::create(['subject_id'=>$subject->id,'status_id'=>'1','term'=>'1','language_id'=>'1','candidate_id'=>$candidate->id,'exam_id'=>'1']);Mark::create(['application_id'=>$application->id, 'exam_id'=>'1', 'candidate_id'=>$candidate->id, 'subject_id'=>$subject->id, 'internal'=>'29','external'=>'37','result_id'=>'1']);
      $candidate=Candidate::where('enrolmentno','271601401')->first(); $subject = Subject::where('scode','01MDAI')->first(); $application = Application::create(['subject_id'=>$subject->id,'status_id'=>'1','term'=>'1','language_id'=>'1','candidate_id'=>$candidate->id,'exam_id'=>'1']);Mark::create(['application_id'=>$application->id, 'exam_id'=>'1', 'candidate_id'=>$candidate->id, 'subject_id'=>$subject->id, 'internal'=>'85','external'=>'50','result_id'=>'1']);
      $candidate=Candidate::where('enrolmentno','271601401')->first(); $subject = Subject::where('scode','01MDGT')->first(); $application = Application::create(['subject_id'=>$subject->id,'status_id'=>'1','term'=>'1','language_id'=>'1','candidate_id'=>$candidate->id,'exam_id'=>'1']);Mark::create(['application_id'=>$application->id, 'exam_id'=>'1', 'candidate_id'=>$candidate->id, 'subject_id'=>$subject->id, 'internal'=>'85','external'=>'52','result_id'=>'1']);
      $candidate=Candidate::where('enrolmentno','271601401')->first(); $subject = Subject::where('scode','01MDGC')->first(); $application = Application::create(['subject_id'=>$subject->id,'status_id'=>'1','term'=>'1','language_id'=>'1','candidate_id'=>$candidate->id,'exam_id'=>'1']);Mark::create(['application_id'=>$application->id, 'exam_id'=>'1', 'candidate_id'=>$candidate->id, 'subject_id'=>$subject->id, 'internal'=>'82','external'=>'53','result_id'=>'1']);
      $candidate=Candidate::where('enrolmentno','271601401')->first(); $subject = Subject::where('scode','01MDTB')->first(); $application = Application::create(['subject_id'=>$subject->id,'status_id'=>'1','term'=>'1','language_id'=>'1','candidate_id'=>$candidate->id,'exam_id'=>'1']);Mark::create(['application_id'=>$application->id, 'exam_id'=>'1', 'candidate_id'=>$candidate->id, 'subject_id'=>$subject->id, 'internal'=>'135','external'=>'96','result_id'=>'1']);
      $candidate=Candidate::where('enrolmentno','271601401')->first(); $subject = Subject::where('scode','01MDIC')->first(); $application = Application::create(['subject_id'=>$subject->id,'status_id'=>'1','term'=>'1','language_id'=>'1','candidate_id'=>$candidate->id,'exam_id'=>'1']);Mark::create(['application_id'=>$application->id, 'exam_id'=>'1', 'candidate_id'=>$candidate->id, 'subject_id'=>$subject->id, 'internal'=>'27','external'=>'18','result_id'=>'1']);
      $candidate=Candidate::where('enrolmentno','271601401')->first(); $subject = Subject::where('scode','01MDTL')->first(); $application = Application::create(['subject_id'=>$subject->id,'status_id'=>'1','term'=>'1','language_id'=>'1','candidate_id'=>$candidate->id,'exam_id'=>'1']);Mark::create(['application_id'=>$application->id, 'exam_id'=>'1', 'candidate_id'=>$candidate->id, 'subject_id'=>$subject->id, 'internal'=>'22','external'=>'14','result_id'=>'1']);
      $candidate=Candidate::where('enrolmentno','271601402')->first(); $subject = Subject::where('scode','01MDID')->first(); $application = Application::create(['subject_id'=>$subject->id,'status_id'=>'1','term'=>'1','language_id'=>'1','candidate_id'=>$candidate->id,'exam_id'=>'1']);Mark::create(['application_id'=>$application->id, 'exam_id'=>'1', 'candidate_id'=>$candidate->id, 'subject_id'=>$subject->id, 'internal'=>'28','external'=>'24','result_id'=>'1']);
      $candidate=Candidate::where('enrolmentno','271601402')->first(); $subject = Subject::where('scode','01MDEP')->first(); $application = Application::create(['subject_id'=>$subject->id,'status_id'=>'1','term'=>'1','language_id'=>'1','candidate_id'=>$candidate->id,'exam_id'=>'1']);Mark::create(['application_id'=>$application->id, 'exam_id'=>'1', 'candidate_id'=>$candidate->id, 'subject_id'=>$subject->id, 'internal'=>'24','external'=>'34','result_id'=>'1']);
      $candidate=Candidate::where('enrolmentno','271601402')->first(); $subject = Subject::where('scode','01MDHD')->first(); $application = Application::create(['subject_id'=>$subject->id,'status_id'=>'1','term'=>'1','language_id'=>'1','candidate_id'=>$candidate->id,'exam_id'=>'1']);Mark::create(['application_id'=>$application->id, 'exam_id'=>'1', 'candidate_id'=>$candidate->id, 'subject_id'=>$subject->id, 'internal'=>'27','external'=>'30','result_id'=>'1']);
      $candidate=Candidate::where('enrolmentno','271601402')->first(); $subject = Subject::where('scode','01MDEA')->first(); $application = Application::create(['subject_id'=>$subject->id,'status_id'=>'1','term'=>'1','language_id'=>'1','candidate_id'=>$candidate->id,'exam_id'=>'1']);Mark::create(['application_id'=>$application->id, 'exam_id'=>'1', 'candidate_id'=>$candidate->id, 'subject_id'=>$subject->id, 'internal'=>'28','external'=>'31','result_id'=>'1']);
      $candidate=Candidate::where('enrolmentno','271601402')->first(); $subject = Subject::where('scode','01MDAA')->first(); $application = Application::create(['subject_id'=>$subject->id,'status_id'=>'1','term'=>'1','language_id'=>'1','candidate_id'=>$candidate->id,'exam_id'=>'1']);Mark::create(['application_id'=>$application->id, 'exam_id'=>'1', 'candidate_id'=>$candidate->id, 'subject_id'=>$subject->id, 'internal'=>'28','external'=>'39','result_id'=>'1']);
      $candidate=Candidate::where('enrolmentno','271601402')->first(); $subject = Subject::where('scode','01MDTM')->first(); $application = Application::create(['subject_id'=>$subject->id,'status_id'=>'1','term'=>'1','language_id'=>'1','candidate_id'=>$candidate->id,'exam_id'=>'1']);Mark::create(['application_id'=>$application->id, 'exam_id'=>'1', 'candidate_id'=>$candidate->id, 'subject_id'=>$subject->id, 'internal'=>'29','external'=>'30','result_id'=>'1']);
      $candidate=Candidate::where('enrolmentno','271601402')->first(); $subject = Subject::where('scode','01MDAI')->first(); $application = Application::create(['subject_id'=>$subject->id,'status_id'=>'1','term'=>'1','language_id'=>'1','candidate_id'=>$candidate->id,'exam_id'=>'1']);Mark::create(['application_id'=>$application->id, 'exam_id'=>'1', 'candidate_id'=>$candidate->id, 'subject_id'=>$subject->id, 'internal'=>'76','external'=>'45','result_id'=>'1']);
      $candidate=Candidate::where('enrolmentno','271601402')->first(); $subject = Subject::where('scode','01MDGT')->first(); $application = Application::create(['subject_id'=>$subject->id,'status_id'=>'1','term'=>'1','language_id'=>'1','candidate_id'=>$candidate->id,'exam_id'=>'1']);Mark::create(['application_id'=>$application->id, 'exam_id'=>'1', 'candidate_id'=>$candidate->id, 'subject_id'=>$subject->id, 'internal'=>'87','external'=>'50','result_id'=>'1']);
      $candidate=Candidate::where('enrolmentno','271601402')->first(); $subject = Subject::where('scode','01MDGC')->first(); $application = Application::create(['subject_id'=>$subject->id,'status_id'=>'1','term'=>'1','language_id'=>'1','candidate_id'=>$candidate->id,'exam_id'=>'1']);Mark::create(['application_id'=>$application->id, 'exam_id'=>'1', 'candidate_id'=>$candidate->id, 'subject_id'=>$subject->id, 'internal'=>'80','external'=>'50','result_id'=>'1']);
      $candidate=Candidate::where('enrolmentno','271601402')->first(); $subject = Subject::where('scode','01MDTB')->first(); $application = Application::create(['subject_id'=>$subject->id,'status_id'=>'1','term'=>'1','language_id'=>'1','candidate_id'=>$candidate->id,'exam_id'=>'1']);Mark::create(['application_id'=>$application->id, 'exam_id'=>'1', 'candidate_id'=>$candidate->id, 'subject_id'=>$subject->id, 'internal'=>'104','external'=>'88','result_id'=>'1']);
      $candidate=Candidate::where('enrolmentno','271601402')->first(); $subject = Subject::where('scode','01MDIC')->first(); $application = Application::create(['subject_id'=>$subject->id,'status_id'=>'1','term'=>'1','language_id'=>'1','candidate_id'=>$candidate->id,'exam_id'=>'1']);Mark::create(['application_id'=>$application->id, 'exam_id'=>'1', 'candidate_id'=>$candidate->id, 'subject_id'=>$subject->id, 'internal'=>'25','external'=>'15','result_id'=>'1']);
      $candidate=Candidate::where('enrolmentno','271601402')->first(); $subject = Subject::where('scode','01MDTL')->first(); $application = Application::create(['subject_id'=>$subject->id,'status_id'=>'1','term'=>'1','language_id'=>'1','candidate_id'=>$candidate->id,'exam_id'=>'1']);Mark::create(['application_id'=>$application->id, 'exam_id'=>'1', 'candidate_id'=>$candidate->id, 'subject_id'=>$subject->id, 'internal'=>'20','external'=>'12','result_id'=>'1']);
      $candidate=Candidate::where('enrolmentno','271601403')->first(); $subject = Subject::where('scode','01MDID')->first(); $application = Application::create(['subject_id'=>$subject->id,'status_id'=>'1','term'=>'1','language_id'=>'1','candidate_id'=>$candidate->id,'exam_id'=>'1']);Mark::create(['application_id'=>$application->id, 'exam_id'=>'1', 'candidate_id'=>$candidate->id, 'subject_id'=>$subject->id, 'internal'=>'Abs','external'=>'Abs','result_id'=>'1']);
      $candidate=Candidate::where('enrolmentno','271601403')->first(); $subject = Subject::where('scode','01MDEP')->first(); $application = Application::create(['subject_id'=>$subject->id,'status_id'=>'1','term'=>'1','language_id'=>'1','candidate_id'=>$candidate->id,'exam_id'=>'1']);Mark::create(['application_id'=>$application->id, 'exam_id'=>'1', 'candidate_id'=>$candidate->id, 'subject_id'=>$subject->id, 'internal'=>'Abs','external'=>'Abs','result_id'=>'1']);
      $candidate=Candidate::where('enrolmentno','271601403')->first(); $subject = Subject::where('scode','01MDHD')->first(); $application = Application::create(['subject_id'=>$subject->id,'status_id'=>'1','term'=>'1','language_id'=>'1','candidate_id'=>$candidate->id,'exam_id'=>'1']);Mark::create(['application_id'=>$application->id, 'exam_id'=>'1', 'candidate_id'=>$candidate->id, 'subject_id'=>$subject->id, 'internal'=>'Abs','external'=>'Abs','result_id'=>'1']);
      $candidate=Candidate::where('enrolmentno','271601403')->first(); $subject = Subject::where('scode','01MDEA')->first(); $application = Application::create(['subject_id'=>$subject->id,'status_id'=>'1','term'=>'1','language_id'=>'1','candidate_id'=>$candidate->id,'exam_id'=>'1']);Mark::create(['application_id'=>$application->id, 'exam_id'=>'1', 'candidate_id'=>$candidate->id, 'subject_id'=>$subject->id, 'internal'=>'Abs','external'=>'Abs','result_id'=>'1']);
      $candidate=Candidate::where('enrolmentno','271601403')->first(); $subject = Subject::where('scode','01MDAA')->first(); $application = Application::create(['subject_id'=>$subject->id,'status_id'=>'1','term'=>'1','language_id'=>'1','candidate_id'=>$candidate->id,'exam_id'=>'1']);Mark::create(['application_id'=>$application->id, 'exam_id'=>'1', 'candidate_id'=>$candidate->id, 'subject_id'=>$subject->id, 'internal'=>'Abs','external'=>'Abs','result_id'=>'1']);
      $candidate=Candidate::where('enrolmentno','271601403')->first(); $subject = Subject::where('scode','01MDTM')->first(); $application = Application::create(['subject_id'=>$subject->id,'status_id'=>'1','term'=>'1','language_id'=>'1','candidate_id'=>$candidate->id,'exam_id'=>'1']);Mark::create(['application_id'=>$application->id, 'exam_id'=>'1', 'candidate_id'=>$candidate->id, 'subject_id'=>$subject->id, 'internal'=>'Abs','external'=>'Abs','result_id'=>'1']);
      $candidate=Candidate::where('enrolmentno','271601403')->first(); $subject = Subject::where('scode','01MDAI')->first(); $application = Application::create(['subject_id'=>$subject->id,'status_id'=>'1','term'=>'1','language_id'=>'1','candidate_id'=>$candidate->id,'exam_id'=>'1']);Mark::create(['application_id'=>$application->id, 'exam_id'=>'1', 'candidate_id'=>$candidate->id, 'subject_id'=>$subject->id, 'internal'=>'Abs','external'=>'Abs','result_id'=>'1']);
      $candidate=Candidate::where('enrolmentno','271601403')->first(); $subject = Subject::where('scode','01MDGT')->first(); $application = Application::create(['subject_id'=>$subject->id,'status_id'=>'1','term'=>'1','language_id'=>'1','candidate_id'=>$candidate->id,'exam_id'=>'1']);Mark::create(['application_id'=>$application->id, 'exam_id'=>'1', 'candidate_id'=>$candidate->id, 'subject_id'=>$subject->id, 'internal'=>'Abs','external'=>'Abs','result_id'=>'1']);
      $candidate=Candidate::where('enrolmentno','271601403')->first(); $subject = Subject::where('scode','01MDGC')->first(); $application = Application::create(['subject_id'=>$subject->id,'status_id'=>'1','term'=>'1','language_id'=>'1','candidate_id'=>$candidate->id,'exam_id'=>'1']);Mark::create(['application_id'=>$application->id, 'exam_id'=>'1', 'candidate_id'=>$candidate->id, 'subject_id'=>$subject->id, 'internal'=>'Abs','external'=>'Abs','result_id'=>'1']);
      $candidate=Candidate::where('enrolmentno','271601403')->first(); $subject = Subject::where('scode','01MDTB')->first(); $application = Application::create(['subject_id'=>$subject->id,'status_id'=>'1','term'=>'1','language_id'=>'1','candidate_id'=>$candidate->id,'exam_id'=>'1']);Mark::create(['application_id'=>$application->id, 'exam_id'=>'1', 'candidate_id'=>$candidate->id, 'subject_id'=>$subject->id, 'internal'=>'Abs','external'=>'Abs','result_id'=>'1']);
      $candidate=Candidate::where('enrolmentno','271601403')->first(); $subject = Subject::where('scode','01MDIC')->first(); $application = Application::create(['subject_id'=>$subject->id,'status_id'=>'1','term'=>'1','language_id'=>'1','candidate_id'=>$candidate->id,'exam_id'=>'1']);Mark::create(['application_id'=>$application->id, 'exam_id'=>'1', 'candidate_id'=>$candidate->id, 'subject_id'=>$subject->id, 'internal'=>'Abs','external'=>'Abs','result_id'=>'1']);
      $candidate=Candidate::where('enrolmentno','271601403')->first(); $subject = Subject::where('scode','01MDTL')->first(); $application = Application::create(['subject_id'=>$subject->id,'status_id'=>'1','term'=>'1','language_id'=>'1','candidate_id'=>$candidate->id,'exam_id'=>'1']);Mark::create(['application_id'=>$application->id, 'exam_id'=>'1', 'candidate_id'=>$candidate->id, 'subject_id'=>$subject->id, 'internal'=>'Abs','external'=>'Abs','result_id'=>'1']);


    }
  }
